language: node_js
node_js:
  - "stable"
env:
  - REACT_APP_DIR=app
cache:
  directories:
    - node_modules
    - $REACT_APP_DIR/node_modules
script:
  - npm run compile
  - cd $REACT_APP_DIR
  - npm ci
  - npm test
  - npm run build
on:
  branch: master
